import type {
  Alert,
  BrightDataTrace,
  Company,
  EvidenceItem,
  ScanStatusResponse,
  VendorReviewBrief,
} from "@/lib/types";

export const demoScanId = "scan_cloudflare_20260526";
export const demoCompanyId = "vendor_cloudflare";

export const companiesFixture: Company[] = [
  {
    id: demoCompanyId,
    name: "Cloudflare",
    domain: "cloudflare.com",
    relationship_type: "edge security",
    owner: "Security",
    criticality: "critical",
    renewal_date: "2026-07-10",
    agent_enabled: false,
    agent_status: "inactive",
    review_policy: null,
    last_agent_run_at: null,
    next_agent_run_at: null,
  },
  {
    id: "vendor_stripe",
    name: "Stripe",
    domain: "stripe.com",
    relationship_type: "payments",
    owner: "Finance",
    criticality: "critical",
    renewal_date: "2026-08-18",
    agent_enabled: true,
    agent_status: "completed",
    review_policy: "weekly",
    last_agent_run_at: "2026-05-25T08:15:00Z",
    next_agent_run_at: "2026-06-01T08:15:00Z",
  },
  {
    id: "vendor_datadog",
    name: "Datadog",
    domain: "datadoghq.com",
    relationship_type: "observability",
    owner: "Data",
    criticality: "important",
    renewal_date: "2026-09-04",
    agent_enabled: true,
    agent_status: "active",
    review_policy: "weekly",
    last_agent_run_at: "2026-05-22T17:40:00Z",
    next_agent_run_at: "2026-05-29T17:40:00Z",
  },
  {
    id: "vendor_auth0",
    name: "Auth0",
    domain: "auth0.com",
    relationship_type: "identity",
    owner: "Engineering",
    criticality: "normal",
    renewal_date: "2026-11-22",
    agent_enabled: false,
    agent_status: "inactive",
    review_policy: null,
    last_agent_run_at: null,
    next_agent_run_at: null,
  },
  {
    id: "vendor_snowflake",
    name: "Snowflake",
    domain: "snowflake.com",
    relationship_type: "data warehouse",
    owner: "Data",
    criticality: "normal",
    renewal_date: "2027-01-20",
    agent_enabled: false,
    agent_status: "inactive",
    review_policy: null,
    last_agent_run_at: null,
    next_agent_run_at: null,
  },
];

export const scanProgression: ScanStatusResponse[] = [
  {
    id: demoScanId,
    company_id: demoCompanyId,
    status: "running",
    mode: "live_with_fallback",
    current_stage: "collect",
    stages: [
      { name: "collect", status: "running" },
      { name: "extract", status: "pending" },
      { name: "verify", status: "pending" },
      { name: "score", status: "pending" },
      { name: "brief", status: "pending" },
    ],
    metrics: {
      serp_queries_used: 1,
      urls_scraped: 1,
      llm_calls_used: 0,
      evidence_count: 0,
      verified_count: 0,
    },
  },
  {
    id: demoScanId,
    company_id: demoCompanyId,
    status: "running",
    mode: "live_with_fallback",
    current_stage: "extract",
    stages: [
      { name: "collect", status: "completed" },
      { name: "extract", status: "running" },
      { name: "verify", status: "pending" },
      { name: "score", status: "pending" },
      { name: "brief", status: "pending" },
    ],
    metrics: {
      serp_queries_used: 1,
      urls_scraped: 1,
      llm_calls_used: 0,
      evidence_count: 1,
      verified_count: 0,
    },
  },
  {
    id: demoScanId,
    company_id: demoCompanyId,
    status: "running",
    mode: "live_with_fallback",
    current_stage: "verify",
    stages: [
      { name: "collect", status: "completed" },
      { name: "extract", status: "completed" },
      { name: "verify", status: "running" },
      { name: "score", status: "pending" },
      { name: "brief", status: "pending" },
    ],
    metrics: {
      serp_queries_used: 1,
      urls_scraped: 1,
      llm_calls_used: 0,
      evidence_count: 3,
      verified_count: 1,
    },
  },
  {
    id: demoScanId,
    company_id: demoCompanyId,
    status: "running",
    mode: "live_with_fallback",
    current_stage: "score",
    stages: [
      { name: "collect", status: "completed" },
      { name: "extract", status: "completed" },
      { name: "verify", status: "completed" },
      { name: "score", status: "running" },
      { name: "brief", status: "pending" },
    ],
    metrics: {
      serp_queries_used: 1,
      urls_scraped: 1,
      llm_calls_used: 0,
      evidence_count: 3,
      verified_count: 3,
    },
  },
  {
    id: demoScanId,
    company_id: demoCompanyId,
    status: "completed_with_fallback",
    mode: "live_with_fallback",
    current_stage: "brief",
    stages: [
      { name: "collect", status: "completed" },
      { name: "extract", status: "completed" },
      { name: "verify", status: "completed" },
      { name: "score", status: "completed" },
      { name: "brief", status: "completed" },
    ],
    metrics: {
      serp_queries_used: 1,
      urls_scraped: 1,
      llm_calls_used: 0,
      evidence_count: 3,
      verified_count: 3,
    },
  },
];

export const evidenceFixture: EvidenceItem[] = [
  {
    id: "evidence_trust_001",
    scan_id: demoScanId,
    company_id: demoCompanyId,
    signal_type: "trust_security",
    claim:
      "Cloudflare publicly identifies SOC 2 Type II and ISO 27001 among its compliance resources.",
    supporting_quote:
      "Explore our posture around ISO 27001, ISO 27701, PCI DSS, SOC 2 Type II, and others.",
    source_url: "https://www.cloudflare.com/trust-hub/",
    source_type: "vendor_owned",
    published_or_captured_at: "2026-05-26T03:45:00Z",
    severity_hint: "medium",
    confidence: 0.95,
    recommended_action:
      "Request the current in-scope compliance package for the renewal record.",
    support_status: "verified",
    quote_match_score: 1,
    source_excerpt:
      "Compliance resources: Explore our posture around ISO 27001, ISO 27701, PCI DSS, SOC 2 Type II, and others.",
  },
  {
    id: "evidence_terms_001",
    scan_id: demoScanId,
    company_id: demoCompanyId,
    signal_type: "pricing_terms",
    claim:
      "Cloudflare identifies Data Localization Suite as an Enterprise-only paid add-on.",
    supporting_quote: "Enterprise-only paid add-on",
    source_url: "https://developers.cloudflare.com/data-localization/",
    source_type: "vendor_owned",
    published_or_captured_at: "2026-05-26T03:47:00Z",
    severity_hint: "high",
    confidence: 0.97,
    recommended_action:
      "Confirm whether regulated-data residency requirements require this add-on in the renewal scope.",
    support_status: "verified",
    quote_match_score: 1,
    source_excerpt:
      "Data Localization Suite: Enterprise-only paid add-on.",
  },
  {
    id: "evidence_media_001",
    scan_id: demoScanId,
    company_id: demoCompanyId,
    signal_type: "adverse_media",
    claim:
      "Cloudflare reported a resolved May 2026 Log Explorer incident that could delay dashboard and API log visibility.",
    supporting_quote:
      "Affected customers may see delays with Cloudflare logs in their dashboard and api.",
    source_url: "https://www.cloudflarestatus.com/",
    source_type: "vendor_owned",
    published_or_captured_at: "2026-05-24T11:20:00Z",
    severity_hint: "medium",
    confidence: 0.94,
    recommended_action:
      "Confirm whether monitoring or audit-log workflows relied on Log Explorer during the incident window.",
    support_status: "verified",
    quote_match_score: 1,
    source_excerpt:
      "Incident impact: Affected customers may see delays with Cloudflare logs in their dashboard and api.",
  },
];

export const tracesFixture: BrightDataTrace[] = [
  {
    id: "trace_serp_001",
    scan_id: demoScanId,
    product: "serp_api",
    operation: "query: cloudflare trust security soc 2 incident terms",
    source_url: "https://www.google.com/search?q=cloudflare+trust+security+soc+2+incident+terms",
    status: "success",
    latency_ms: 816,
    retry_count: 0,
    error: null,
    source_mode: "live",
    created_at: "2026-05-26T03:44:12Z",
  },
  {
    id: "trace_unlocker_001",
    scan_id: demoScanId,
    product: "web_unlocker",
    operation: "scrape_markdown:configured_demo_source",
    source_url: "https://www.cloudflare.com/trust-hub/",
    status: "success",
    latency_ms: 1088,
    retry_count: 0,
    error: null,
    source_mode: "live",
    created_at: "2026-05-26T03:45:01Z",
  },
  {
    id: "trace_cache_trust_001",
    scan_id: demoScanId,
    product: "markdown_scrape",
    operation: "scrape_markdown",
    source_url: "https://www.cloudflare.com/trust-hub/",
    status: "fallback_used",
    latency_ms: 22,
    retry_count: 0,
    error: null,
    source_mode: "fallback",
    created_at: "2026-05-26T03:46:38Z",
  },
  {
    id: "trace_cache_terms_001",
    scan_id: demoScanId,
    product: "replay_loader",
    operation: "load_cached_source",
    source_url: "https://developers.cloudflare.com/data-localization/",
    status: "fallback_used",
    latency_ms: 22,
    retry_count: 0,
    error: null,
    source_mode: "fallback",
    created_at: "2026-05-26T03:46:39Z",
  },
  {
    id: "trace_cache_status_001",
    scan_id: demoScanId,
    product: "markdown_scrape",
    operation: "scrape_markdown",
    source_url: "https://www.cloudflarestatus.com/",
    status: "fallback_used",
    latency_ms: 18,
    retry_count: 0,
    error: null,
    source_mode: "fallback",
    created_at: "2026-05-26T03:47:10Z",
  },
];

export const alertsFixture: Alert[] = [
  {
    id: "alert_terms_001",
    company_id: demoCompanyId,
    scan_id: demoScanId,
    evidence_item_id: "evidence_terms_001",
    alert_type: "signal",
    title: "Data localization add-on requires renewal scope review",
    summary:
      "Verified public documentation identifies Data Localization Suite as an Enterprise-only paid add-on.",
    score: 75,
    severity: "high",
    status: "new",
    owner: "Procurement",
    recommended_action:
      "Confirm data residency requirements and commercial scope before renewal approval.",
    related_evidence_ids: ["evidence_terms_001"],
    score_factors: {
      base_severity: 0.9,
      source_reliability: 0.9,
      confidence: 0.97,
      freshness: 0.99,
      vendor_criticality: 1.2,
    },
    created_at: "2026-05-26T03:48:00Z",
  },
  {
    id: "alert_related_001",
    company_id: demoCompanyId,
    scan_id: demoScanId,
    evidence_item_id: null,
    alert_type: "related_change",
    title: "Renewal checkpoint: compliance evidence and data residency scope",
    summary:
      "Verified Cloudflare public sources identify compliance resources and an Enterprise-only data localization add-on relevant to due diligence.",
    score: 78,
    severity: "high",
    status: "new",
    owner: "Security",
    recommended_action:
      "Review compliance artifacts and regulated-data hosting needs together with Procurement.",
    related_evidence_ids: ["evidence_trust_001", "evidence_terms_001"],
    score_factors: {
      rule: "two_verified_compatible_signals",
      verified_evidence_count: 2,
      unsupported_evidence_excluded: 0,
    },
    created_at: "2026-05-26T03:49:00Z",
  },
];

export const briefFixture: VendorReviewBrief = {
  company_id: demoCompanyId,
  scan_id: demoScanId,
  format: "markdown",
  content:
    "# Vendor Risk Assessment Brief: Cloudflare\n\n## Summary\nCloudflare is a critical edge security vendor with renewal approaching. Pulse found three verified public signals from Cloudflare-owned pages in its curated fallback review.\n\n## Key verified signals\n- Cloudflare lists ISO 27001, ISO 27701, PCI DSS, and SOC 2 Type II among its compliance resources.\n- Data Localization Suite is identified as an Enterprise-only paid add-on.\n- Cloudflare reported that affected customers could see dashboard and API log delays during a resolved Log Explorer incident.\n\n## Risk interpretation\nThese signals do not establish a security breach or control failure. They create a review checkpoint for compliance evidence, commercial data-localization scope, and monitoring impact.\n\n## Recommended action\nSecurity and Procurement should request the applicable compliance package and confirm Data Localization Suite requirements before signature.\n\n## Suggested owner\nSecurity with Procurement support.\n\n## Review status\nCompleted with fallback. Live Bright Data collection telemetry is shown separately, while this brief remains based on verified cached fallback excerpts.",
};
